# Generated by Django 4.2 on 2024-07-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_addmyproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmyproject',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addmyproject',
            name='sector',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addmyproject',
            name='sub_sector',
            field=models.CharField(max_length=100),
        ),
    ]
