# Generated by Django 4.2 on 2024-07-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_alter_addmyproject_role_alter_addmyproject_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmyproject',
            name='description',
            field=models.TextField(),
        ),
    ]
