# Generated by Django 4.2 on 2024-07-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_remove_communitypost_pdf_remove_communitypost_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='description',
            field=models.TextField(default='default_description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='sub_sector',
            field=models.CharField(default='default_sub_sector', max_length=100, verbose_name='sub_sector'),
        ),
    ]
