# Generated by Django 4.2 on 2024-07-24 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0012_alter_communitypost_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='sector')),
            ],
        ),
        migrations.CreateModel(
            name='SubSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='subsector')),
            ],
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.sector', verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='sub_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.subsector', verbose_name='subsector'),
        ),
    ]
