# Generated by Django 4.2 on 2024-07-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_sector_subsector_alter_communitypost_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='sub_sector',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='SubSector',
        ),
    ]
