# Generated by Django 4.2 on 2024-07-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0014_remove_communitypost_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='sector',
            field=models.CharField(default='default_sector', max_length=100),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='sub_sector',
            field=models.CharField(default='default_sub_sector', max_length=100),
        ),
    ]
