# Generated by Django 5.0.7 on 2024-07-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0015_communitypost_sector_communitypost_sub_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
