# Generated by Django 5.0.7 on 2024-07-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0016_communitypost_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
