# Generated by Django 5.0.3 on 2024-05-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliedfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chatbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('investment_needed', models.TextField()),
                ('typeofpost', models.CharField(default='', max_length=128)),
                ('location', models.CharField(default='', max_length=256)),
                ('company_name', models.CharField(default='', max_length=256)),
                ('website', models.CharField(default='', max_length=256)),
                ('duration', models.TextField()),
                ('skills', models.TextField()),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
