# Generated by Django 5.0 on 2024-05-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_contact_faq_review_subscribe_tags_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
