# Generated by Django 5.0.3 on 2024-05-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='featured_alt_text',
        ),
        migrations.RemoveField(
            model_name='category',
            name='featured_title',
        ),
    ]
