# Generated by Django 5.0.3 on 2024-05-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='../static/theme-assets/images/avatar/05.jpg', null=True, upload_to='profile/'),
        ),
    ]
